# Generated by Django 5.0.3 on 2024-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sellerproducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sellerid", models.CharField(max_length=250)),
                ("productname", models.CharField(max_length=250)),
                ("category", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("modelnumber", models.IntegerField()),
                ("measurement", models.CharField(max_length=250)),
            ],
        ),
    ]
