# Generated by Django 5.0.3 on 2024-04-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_sellerproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterialoredrsub",
            name="RAWMATERIAL",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.rawmaterials",
            ),
        ),
    ]
