# Generated by Django 5.0.3 on 2024-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_rawmaterialoredrsub_rawmaterial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasesub",
            name="product",
        ),
    ]
