# Generated by Django 5.0.3 on 2024-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_purchasesub_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasesub",
            name="product",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
