# Generated by Django 5.0.3 on 2024-04-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_purchasesub_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sellerordermain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                (
                    "SELLER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sellerordersub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(max_length=100)),
                (
                    "MANUFACTUREPRODUCT",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.manufactureproducts",
                    ),
                ),
                (
                    "SELLERORDERMAIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.customerordermain",
                    ),
                ),
            ],
        ),
    ]
