# Generated by Django 5.0.3 on 2024-04-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_purchasemain_product_alter_purchasemain_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="productordermain",
            name="USER",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
            preserve_default=False,
        ),
    ]
