# Generated by Django 4.0.1 on 2024-04-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_modelnumber_sellerproducts_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialoredrsub',
            name='RAWMATERIAL',
        ),
        migrations.RemoveField(
            model_name='rawmaterialoredrsub',
            name='productdescription',
        ),
        migrations.RemoveField(
            model_name='stockrawmaterial',
            name='RAWMATERIAL',
        ),
        migrations.AddField(
            model_name='rawmaterialoredrsub',
            name='RAWMATERIAL_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrawmaterial',
            name='RAWMATERIAL_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrawmaterial',
            name='SUPPLIER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier'),
            preserve_default=False,
        ),
    ]
