# Generated by Django 4.0.1 on 2024-04-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_productsub_productsubordermain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsub',
            name='PRODUCTSUBORDERMAIN_id',
        ),
        migrations.RemoveField(
            model_name='sellerordersub',
            name='MANUFACTUREPRODUCT',
        ),
        migrations.AddField(
            model_name='productsub',
            name='PRODUCTSUBORDERMAIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.productordermain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerordersub',
            name='MANUFACTUREPRODUCT_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
