# Generated by Django 4.0.1 on 2024-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_productsub_productsubordermain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='dateofbirth',
            field=models.CharField(max_length=15),
        ),
    ]
