# Generated by Django 4.0.1 on 2024-04-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_seller_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordersub',
            name='MANUFACTUREPRODUCT',
        ),
        migrations.AddField(
            model_name='customerordersub',
            name='MANUFACTUREPRODUCT_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
