# Generated by Django 4.0.1 on 2024-04-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_customerordersub_manufactureproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerordermain',
            name='amount',
        ),
        migrations.AlterField(
            model_name='sellerordersub',
            name='SELLERORDERMAIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sellerordermain'),
        ),
    ]
