# Generated by Django 4.0.1 on 2024-04-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_sellerordermain_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproducts',
            name='PURCHASESUB',
        ),
        migrations.AddField(
            model_name='sellerproducts',
            name='SELLERORDERSUB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sellerordersub'),
            preserve_default=False,
        ),
    ]
