# Generated by Django 4.0.1 on 2024-04-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_sellerproducts_purchasesub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
